camel:
  server-port: ${PORT:5000}
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

kafka:
  bootstrapAddress: "127.0.0.1:9092"
  topic:
    slcb:
      name: slcb

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 8
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
  broker:
    contactpoint: "127.0.0.1:26500"

slcb:
  auth:
    host: https://g2p-test.slcb.com:8443
    auth-endpoint: /api/auth
    username: ${SLCB_USERNAME:username}
    password: ${SLCB_PASSWORD:password}
  api:
    host: https://g2p-test.slcb.com:8443
    transaction-request-endpoint: /api/transactionRequest
    reconciliation-endpoint: /reconciliation
    account-balance-endpoint: /accountBalance
  signature:
    key: ${SLCB_SIGNATURE_KEY:very_long_string}

dfspids: "DFSPID"
